language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

before_script:
  - composer self-update
  - composer install

script:
  - mkdir temp
  - make stan
  - make cs
  - vendor/bin/phpunit --configuration phpunit.xml src --coverage-clover=coverage.clover

after_script:
  # upload clover.xml file to Scrutinizer to analyze it
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
